//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSCountry
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="SMSCountry WebService", ConfigurationName="SMSCountry.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/getInbox", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCountry.getInboxResponse> getInboxAsync(SMSCountry.getInboxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/MarkRead_inbox", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCountry.MarkRead_inboxResponse> MarkRead_inboxAsync(SMSCountry.MarkRead_inboxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/Mark_UnRead_inbox", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCountry.Mark_UnRead_inboxResponse> Mark_UnRead_inboxAsync(SMSCountry.Mark_UnRead_inboxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendTextSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCountry.SendTextSMSResponse> SendTextSMSAsync(SMSCountry.SendTextSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendUnicodeSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCountry.SendUnicodeSMSResponse> SendUnicodeSMSAsync(SMSCountry.SendUnicodeSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendPictureSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCountry.SendPictureSMSResponse> SendPictureSMSAsync(SMSCountry.SendPictureSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendBinarySMS", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCountry.SendBinarySMSResponse> SendBinarySMSAsync(SMSCountry.SendBinarySMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendRingTone", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCountry.SendRingToneResponse> SendRingToneAsync(SMSCountry.SendRingToneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendLOGO", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCountry.SendLOGOResponse> SendLOGOAsync(SMSCountry.SendLOGORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendWapPush", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCountry.SendWapPushResponse> SendWapPushAsync(SMSCountry.SendWapPushRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendFlashSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCountry.SendFlashSMSResponse> SendFlashSMSAsync(SMSCountry.SendFlashSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/Getbalance", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCountry.GetbalanceResponse> GetbalanceAsync(SMSCountry.GetbalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/GetDeliveryReport", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCountry.GetDeliveryReportResponse> GetDeliveryReportAsync(SMSCountry.GetDeliveryReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/sendMultiSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCountry.sendMultiSMSResponse> sendMultiSMSAsync(SMSCountry.sendMultiSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInboxRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInbox", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.getInboxRequestBody Body;
        
        public getInboxRequest()
        {
        }
        
        public getInboxRequest(SMSCountry.getInboxRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class getInboxRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ToDate;
        
        public getInboxRequestBody()
        {
        }
        
        public getInboxRequestBody(string username, string password, string FromDate, string ToDate)
        {
            this.username = username;
            this.password = password;
            this.FromDate = FromDate;
            this.ToDate = ToDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInboxResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInboxResponse", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.getInboxResponseBody Body;
        
        public getInboxResponse()
        {
        }
        
        public getInboxResponse(SMSCountry.getInboxResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class getInboxResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getInboxResult;
        
        public getInboxResponseBody()
        {
        }
        
        public getInboxResponseBody(string getInboxResult)
        {
            this.getInboxResult = getInboxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarkRead_inboxRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarkRead_inbox", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.MarkRead_inboxRequestBody Body;
        
        public MarkRead_inboxRequest()
        {
        }
        
        public MarkRead_inboxRequest(SMSCountry.MarkRead_inboxRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class MarkRead_inboxRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int msgid;
        
        public MarkRead_inboxRequestBody()
        {
        }
        
        public MarkRead_inboxRequestBody(string username, string password, int msgid)
        {
            this.username = username;
            this.password = password;
            this.msgid = msgid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarkRead_inboxResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarkRead_inboxResponse", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.MarkRead_inboxResponseBody Body;
        
        public MarkRead_inboxResponse()
        {
        }
        
        public MarkRead_inboxResponse(SMSCountry.MarkRead_inboxResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class MarkRead_inboxResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MarkRead_inboxResult;
        
        public MarkRead_inboxResponseBody()
        {
        }
        
        public MarkRead_inboxResponseBody(string MarkRead_inboxResult)
        {
            this.MarkRead_inboxResult = MarkRead_inboxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Mark_UnRead_inboxRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Mark_UnRead_inbox", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.Mark_UnRead_inboxRequestBody Body;
        
        public Mark_UnRead_inboxRequest()
        {
        }
        
        public Mark_UnRead_inboxRequest(SMSCountry.Mark_UnRead_inboxRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class Mark_UnRead_inboxRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int msgid;
        
        public Mark_UnRead_inboxRequestBody()
        {
        }
        
        public Mark_UnRead_inboxRequestBody(string username, string password, int msgid)
        {
            this.username = username;
            this.password = password;
            this.msgid = msgid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Mark_UnRead_inboxResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Mark_UnRead_inboxResponse", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.Mark_UnRead_inboxResponseBody Body;
        
        public Mark_UnRead_inboxResponse()
        {
        }
        
        public Mark_UnRead_inboxResponse(SMSCountry.Mark_UnRead_inboxResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class Mark_UnRead_inboxResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mark_UnRead_inboxResult;
        
        public Mark_UnRead_inboxResponseBody()
        {
        }
        
        public Mark_UnRead_inboxResponseBody(string Mark_UnRead_inboxResult)
        {
            this.Mark_UnRead_inboxResult = Mark_UnRead_inboxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTextSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTextSMS", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.SendTextSMSRequestBody Body;
        
        public SendTextSMSRequest()
        {
        }
        
        public SendTextSMSRequest(SMSCountry.SendTextSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendTextSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string senderID;
        
        public SendTextSMSRequestBody()
        {
        }
        
        public SendTextSMSRequestBody(string username, string password, string mobilenumbers, string message, string senderID)
        {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.senderID = senderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTextSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTextSMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.SendTextSMSResponseBody Body;
        
        public SendTextSMSResponse()
        {
        }
        
        public SendTextSMSResponse(SMSCountry.SendTextSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendTextSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendTextSMSResult;
        
        public SendTextSMSResponseBody()
        {
        }
        
        public SendTextSMSResponseBody(string SendTextSMSResult)
        {
            this.SendTextSMSResult = SendTextSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendUnicodeSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendUnicodeSMS", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.SendUnicodeSMSRequestBody Body;
        
        public SendUnicodeSMSRequest()
        {
        }
        
        public SendUnicodeSMSRequest(SMSCountry.SendUnicodeSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendUnicodeSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string senderID;
        
        public SendUnicodeSMSRequestBody()
        {
        }
        
        public SendUnicodeSMSRequestBody(string username, string password, string mobilenumbers, string message, string senderID)
        {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.senderID = senderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendUnicodeSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendUnicodeSMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.SendUnicodeSMSResponseBody Body;
        
        public SendUnicodeSMSResponse()
        {
        }
        
        public SendUnicodeSMSResponse(SMSCountry.SendUnicodeSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendUnicodeSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendUnicodeSMSResult;
        
        public SendUnicodeSMSResponseBody()
        {
        }
        
        public SendUnicodeSMSResponseBody(string SendUnicodeSMSResult)
        {
            this.SendUnicodeSMSResult = SendUnicodeSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPictureSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPictureSMS", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.SendPictureSMSRequestBody Body;
        
        public SendPictureSMSRequest()
        {
        }
        
        public SendPictureSMSRequest(SMSCountry.SendPictureSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendPictureSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        public SendPictureSMSRequestBody()
        {
        }
        
        public SendPictureSMSRequestBody(string username, string password, string mobilenumbers, string message, string SenderID)
        {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPictureSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPictureSMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.SendPictureSMSResponseBody Body;
        
        public SendPictureSMSResponse()
        {
        }
        
        public SendPictureSMSResponse(SMSCountry.SendPictureSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendPictureSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendPictureSMSResult;
        
        public SendPictureSMSResponseBody()
        {
        }
        
        public SendPictureSMSResponseBody(string SendPictureSMSResult)
        {
            this.SendPictureSMSResult = SendPictureSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBinarySMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBinarySMS", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.SendBinarySMSRequestBody Body;
        
        public SendBinarySMSRequest()
        {
        }
        
        public SendBinarySMSRequest(SMSCountry.SendBinarySMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendBinarySMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        public SendBinarySMSRequestBody()
        {
        }
        
        public SendBinarySMSRequestBody(string username, string password, string mobilenumbers, string message, string SenderID)
        {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBinarySMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBinarySMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.SendBinarySMSResponseBody Body;
        
        public SendBinarySMSResponse()
        {
        }
        
        public SendBinarySMSResponse(SMSCountry.SendBinarySMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendBinarySMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendBinarySMSResult;
        
        public SendBinarySMSResponseBody()
        {
        }
        
        public SendBinarySMSResponseBody(string SendBinarySMSResult)
        {
            this.SendBinarySMSResult = SendBinarySMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRingToneRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRingTone", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.SendRingToneRequestBody Body;
        
        public SendRingToneRequest()
        {
        }
        
        public SendRingToneRequest(SMSCountry.SendRingToneRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendRingToneRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        public SendRingToneRequestBody()
        {
        }
        
        public SendRingToneRequestBody(string username, string password, string mobilenumbers, string message, string SenderID)
        {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRingToneResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRingToneResponse", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.SendRingToneResponseBody Body;
        
        public SendRingToneResponse()
        {
        }
        
        public SendRingToneResponse(SMSCountry.SendRingToneResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendRingToneResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendRingToneResult;
        
        public SendRingToneResponseBody()
        {
        }
        
        public SendRingToneResponseBody(string SendRingToneResult)
        {
            this.SendRingToneResult = SendRingToneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendLOGORequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendLOGO", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.SendLOGORequestBody Body;
        
        public SendLOGORequest()
        {
        }
        
        public SendLOGORequest(SMSCountry.SendLOGORequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendLOGORequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        public SendLOGORequestBody()
        {
        }
        
        public SendLOGORequestBody(string username, string password, string mobilenumbers, string message, string SenderID)
        {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendLOGOResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendLOGOResponse", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.SendLOGOResponseBody Body;
        
        public SendLOGOResponse()
        {
        }
        
        public SendLOGOResponse(SMSCountry.SendLOGOResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendLOGOResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendLOGOResult;
        
        public SendLOGOResponseBody()
        {
        }
        
        public SendLOGOResponseBody(string SendLOGOResult)
        {
            this.SendLOGOResult = SendLOGOResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWapPushRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWapPush", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.SendWapPushRequestBody Body;
        
        public SendWapPushRequest()
        {
        }
        
        public SendWapPushRequest(SMSCountry.SendWapPushRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendWapPushRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string WapUrl;
        
        public SendWapPushRequestBody()
        {
        }
        
        public SendWapPushRequestBody(string username, string password, string mobilenumbers, string message, string SenderID, string WapUrl)
        {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
            this.WapUrl = WapUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWapPushResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWapPushResponse", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.SendWapPushResponseBody Body;
        
        public SendWapPushResponse()
        {
        }
        
        public SendWapPushResponse(SMSCountry.SendWapPushResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendWapPushResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendWapPushResult;
        
        public SendWapPushResponseBody()
        {
        }
        
        public SendWapPushResponseBody(string SendWapPushResult)
        {
            this.SendWapPushResult = SendWapPushResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFlashSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendFlashSMS", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.SendFlashSMSRequestBody Body;
        
        public SendFlashSMSRequest()
        {
        }
        
        public SendFlashSMSRequest(SMSCountry.SendFlashSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendFlashSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        public SendFlashSMSRequestBody()
        {
        }
        
        public SendFlashSMSRequestBody(string username, string password, string mobilenumbers, string message, string SenderID)
        {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFlashSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendFlashSMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.SendFlashSMSResponseBody Body;
        
        public SendFlashSMSResponse()
        {
        }
        
        public SendFlashSMSResponse(SMSCountry.SendFlashSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendFlashSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendFlashSMSResult;
        
        public SendFlashSMSResponseBody()
        {
        }
        
        public SendFlashSMSResponseBody(string SendFlashSMSResult)
        {
            this.SendFlashSMSResult = SendFlashSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetbalanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Getbalance", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.GetbalanceRequestBody Body;
        
        public GetbalanceRequest()
        {
        }
        
        public GetbalanceRequest(SMSCountry.GetbalanceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class GetbalanceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetbalanceRequestBody()
        {
        }
        
        public GetbalanceRequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetbalanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetbalanceResponse", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.GetbalanceResponseBody Body;
        
        public GetbalanceResponse()
        {
        }
        
        public GetbalanceResponse(SMSCountry.GetbalanceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class GetbalanceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetbalanceResult;
        
        public GetbalanceResponseBody()
        {
        }
        
        public GetbalanceResponseBody(string GetbalanceResult)
        {
            this.GetbalanceResult = GetbalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeliveryReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeliveryReport", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.GetDeliveryReportRequestBody Body;
        
        public GetDeliveryReportRequest()
        {
        }
        
        public GetDeliveryReportRequest(SMSCountry.GetDeliveryReportRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class GetDeliveryReportRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ulong SMS_Job_No;
        
        public GetDeliveryReportRequestBody()
        {
        }
        
        public GetDeliveryReportRequestBody(string username, string password, ulong SMS_Job_No)
        {
            this.username = username;
            this.password = password;
            this.SMS_Job_No = SMS_Job_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeliveryReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeliveryReportResponse", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.GetDeliveryReportResponseBody Body;
        
        public GetDeliveryReportResponse()
        {
        }
        
        public GetDeliveryReportResponse(SMSCountry.GetDeliveryReportResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class GetDeliveryReportResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDeliveryReportResult;
        
        public GetDeliveryReportResponseBody()
        {
        }
        
        public GetDeliveryReportResponseBody(string GetDeliveryReportResult)
        {
            this.GetDeliveryReportResult = GetDeliveryReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMultiSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMultiSMS", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.sendMultiSMSRequestBody Body;
        
        public sendMultiSMSRequest()
        {
        }
        
        public sendMultiSMSRequest(SMSCountry.sendMultiSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class sendMultiSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MNO_MSG;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mtype;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public ushort dr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string wapurl;
        
        public sendMultiSMSRequestBody()
        {
        }
        
        public sendMultiSMSRequestBody(string user, string password, string MNO_MSG, string sid, string mtype, ushort dr, string wapurl)
        {
            this.user = user;
            this.password = password;
            this.MNO_MSG = MNO_MSG;
            this.sid = sid;
            this.mtype = mtype;
            this.dr = dr;
            this.wapurl = wapurl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMultiSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMultiSMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public SMSCountry.sendMultiSMSResponseBody Body;
        
        public sendMultiSMSResponse()
        {
        }
        
        public sendMultiSMSResponse(SMSCountry.sendMultiSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class sendMultiSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendMultiSMSResult;
        
        public sendMultiSMSResponseBody()
        {
        }
        
        public sendMultiSMSResponseBody(string sendMultiSMSResult)
        {
            this.sendMultiSMSResult = sendMultiSMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ServiceSoapChannel : SMSCountry.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SMSCountry.ServiceSoap>, SMSCountry.ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCountry.getInboxResponse> SMSCountry.ServiceSoap.getInboxAsync(SMSCountry.getInboxRequest request)
        {
            return base.Channel.getInboxAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCountry.getInboxResponse> getInboxAsync(string username, string password, string FromDate, string ToDate)
        {
            SMSCountry.getInboxRequest inValue = new SMSCountry.getInboxRequest();
            inValue.Body = new SMSCountry.getInboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.FromDate = FromDate;
            inValue.Body.ToDate = ToDate;
            return ((SMSCountry.ServiceSoap)(this)).getInboxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCountry.MarkRead_inboxResponse> SMSCountry.ServiceSoap.MarkRead_inboxAsync(SMSCountry.MarkRead_inboxRequest request)
        {
            return base.Channel.MarkRead_inboxAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCountry.MarkRead_inboxResponse> MarkRead_inboxAsync(string username, string password, int msgid)
        {
            SMSCountry.MarkRead_inboxRequest inValue = new SMSCountry.MarkRead_inboxRequest();
            inValue.Body = new SMSCountry.MarkRead_inboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.msgid = msgid;
            return ((SMSCountry.ServiceSoap)(this)).MarkRead_inboxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCountry.Mark_UnRead_inboxResponse> SMSCountry.ServiceSoap.Mark_UnRead_inboxAsync(SMSCountry.Mark_UnRead_inboxRequest request)
        {
            return base.Channel.Mark_UnRead_inboxAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCountry.Mark_UnRead_inboxResponse> Mark_UnRead_inboxAsync(string username, string password, int msgid)
        {
            SMSCountry.Mark_UnRead_inboxRequest inValue = new SMSCountry.Mark_UnRead_inboxRequest();
            inValue.Body = new SMSCountry.Mark_UnRead_inboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.msgid = msgid;
            return ((SMSCountry.ServiceSoap)(this)).Mark_UnRead_inboxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCountry.SendTextSMSResponse> SMSCountry.ServiceSoap.SendTextSMSAsync(SMSCountry.SendTextSMSRequest request)
        {
            return base.Channel.SendTextSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCountry.SendTextSMSResponse> SendTextSMSAsync(string username, string password, string mobilenumbers, string message, string senderID)
        {
            SMSCountry.SendTextSMSRequest inValue = new SMSCountry.SendTextSMSRequest();
            inValue.Body = new SMSCountry.SendTextSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.senderID = senderID;
            return ((SMSCountry.ServiceSoap)(this)).SendTextSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCountry.SendUnicodeSMSResponse> SMSCountry.ServiceSoap.SendUnicodeSMSAsync(SMSCountry.SendUnicodeSMSRequest request)
        {
            return base.Channel.SendUnicodeSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCountry.SendUnicodeSMSResponse> SendUnicodeSMSAsync(string username, string password, string mobilenumbers, string message, string senderID)
        {
            SMSCountry.SendUnicodeSMSRequest inValue = new SMSCountry.SendUnicodeSMSRequest();
            inValue.Body = new SMSCountry.SendUnicodeSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.senderID = senderID;
            return ((SMSCountry.ServiceSoap)(this)).SendUnicodeSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCountry.SendPictureSMSResponse> SMSCountry.ServiceSoap.SendPictureSMSAsync(SMSCountry.SendPictureSMSRequest request)
        {
            return base.Channel.SendPictureSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCountry.SendPictureSMSResponse> SendPictureSMSAsync(string username, string password, string mobilenumbers, string message, string SenderID)
        {
            SMSCountry.SendPictureSMSRequest inValue = new SMSCountry.SendPictureSMSRequest();
            inValue.Body = new SMSCountry.SendPictureSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            return ((SMSCountry.ServiceSoap)(this)).SendPictureSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCountry.SendBinarySMSResponse> SMSCountry.ServiceSoap.SendBinarySMSAsync(SMSCountry.SendBinarySMSRequest request)
        {
            return base.Channel.SendBinarySMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCountry.SendBinarySMSResponse> SendBinarySMSAsync(string username, string password, string mobilenumbers, string message, string SenderID)
        {
            SMSCountry.SendBinarySMSRequest inValue = new SMSCountry.SendBinarySMSRequest();
            inValue.Body = new SMSCountry.SendBinarySMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            return ((SMSCountry.ServiceSoap)(this)).SendBinarySMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCountry.SendRingToneResponse> SMSCountry.ServiceSoap.SendRingToneAsync(SMSCountry.SendRingToneRequest request)
        {
            return base.Channel.SendRingToneAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCountry.SendRingToneResponse> SendRingToneAsync(string username, string password, string mobilenumbers, string message, string SenderID)
        {
            SMSCountry.SendRingToneRequest inValue = new SMSCountry.SendRingToneRequest();
            inValue.Body = new SMSCountry.SendRingToneRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            return ((SMSCountry.ServiceSoap)(this)).SendRingToneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCountry.SendLOGOResponse> SMSCountry.ServiceSoap.SendLOGOAsync(SMSCountry.SendLOGORequest request)
        {
            return base.Channel.SendLOGOAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCountry.SendLOGOResponse> SendLOGOAsync(string username, string password, string mobilenumbers, string message, string SenderID)
        {
            SMSCountry.SendLOGORequest inValue = new SMSCountry.SendLOGORequest();
            inValue.Body = new SMSCountry.SendLOGORequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            return ((SMSCountry.ServiceSoap)(this)).SendLOGOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCountry.SendWapPushResponse> SMSCountry.ServiceSoap.SendWapPushAsync(SMSCountry.SendWapPushRequest request)
        {
            return base.Channel.SendWapPushAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCountry.SendWapPushResponse> SendWapPushAsync(string username, string password, string mobilenumbers, string message, string SenderID, string WapUrl)
        {
            SMSCountry.SendWapPushRequest inValue = new SMSCountry.SendWapPushRequest();
            inValue.Body = new SMSCountry.SendWapPushRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            inValue.Body.WapUrl = WapUrl;
            return ((SMSCountry.ServiceSoap)(this)).SendWapPushAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCountry.SendFlashSMSResponse> SMSCountry.ServiceSoap.SendFlashSMSAsync(SMSCountry.SendFlashSMSRequest request)
        {
            return base.Channel.SendFlashSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCountry.SendFlashSMSResponse> SendFlashSMSAsync(string username, string password, string mobilenumbers, string message, string SenderID)
        {
            SMSCountry.SendFlashSMSRequest inValue = new SMSCountry.SendFlashSMSRequest();
            inValue.Body = new SMSCountry.SendFlashSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            return ((SMSCountry.ServiceSoap)(this)).SendFlashSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCountry.GetbalanceResponse> SMSCountry.ServiceSoap.GetbalanceAsync(SMSCountry.GetbalanceRequest request)
        {
            return base.Channel.GetbalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCountry.GetbalanceResponse> GetbalanceAsync(string username, string password)
        {
            SMSCountry.GetbalanceRequest inValue = new SMSCountry.GetbalanceRequest();
            inValue.Body = new SMSCountry.GetbalanceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((SMSCountry.ServiceSoap)(this)).GetbalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCountry.GetDeliveryReportResponse> SMSCountry.ServiceSoap.GetDeliveryReportAsync(SMSCountry.GetDeliveryReportRequest request)
        {
            return base.Channel.GetDeliveryReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCountry.GetDeliveryReportResponse> GetDeliveryReportAsync(string username, string password, ulong SMS_Job_No)
        {
            SMSCountry.GetDeliveryReportRequest inValue = new SMSCountry.GetDeliveryReportRequest();
            inValue.Body = new SMSCountry.GetDeliveryReportRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.SMS_Job_No = SMS_Job_No;
            return ((SMSCountry.ServiceSoap)(this)).GetDeliveryReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCountry.sendMultiSMSResponse> SMSCountry.ServiceSoap.sendMultiSMSAsync(SMSCountry.sendMultiSMSRequest request)
        {
            return base.Channel.sendMultiSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCountry.sendMultiSMSResponse> sendMultiSMSAsync(string user, string password, string MNO_MSG, string sid, string mtype, ushort dr, string wapurl)
        {
            SMSCountry.sendMultiSMSRequest inValue = new SMSCountry.sendMultiSMSRequest();
            inValue.Body = new SMSCountry.sendMultiSMSRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.MNO_MSG = MNO_MSG;
            inValue.Body.sid = sid;
            inValue.Body.mtype = mtype;
            inValue.Body.dr = dr;
            inValue.Body.wapurl = wapurl;
            return ((SMSCountry.ServiceSoap)(this)).sendMultiSMSAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.smscountry.com/service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.smscountry.com/service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
